### PR TITLE
Preserve cgo's import "C"

### LINKED ISSUE #56: incorrect behavior with cgo "import C"
When using golang with cgo, we have a preamble with C headers, followed by `import "C"`, and then our go imports, ie

```
/*
#include <stdlib.h>
*/
import "C"

import (
	"errors"
	"fmt"
)
```

After running `goimports-reviser`, the `import "C"` is not preserved in its current position, which is required in order to use cgo

Am I missing something?

### PR DESCRIPTION
**Pull request by fmeum**
cgo's import "C" has a special meaning as well as a relevant doc comment and should thus never be regrouped. With this commit, it is ignored by all functions that track or mutate imports.

Fixes #56.

@sudssm Could you verify that this fixes the handling of cgo imports for you?

### CODE REVIEW

**Comment by fmeum** [comment]
The tests emit data into `testdata`, which confuses follow-up tests. I think that it would be better to write the test files to a directory created via [ioutil.TempDir](https://pkg.go.dev/io/ioutil#TempDir).

**Comment by incu6us** [comment]
it appears, because cgo_example.go and example.go has different package definitions. change for a single one will fix the error

File: reviser/reviser.go [hunk 1]
```diff
@@ -238,6 +238,19 @@ func generateFile(fset *token.FileSet, f *ast.File) ([]byte, error) {
...
 }
 
+func isSingleCgoImport(dd *ast.GenDecl) bool {
+	if dd.Tok != token.IMPORT {
+		return false
+	}
+	if len(dd.Specs) != 1 {
+		return false
+	}
+	if dd.Specs[0].(*ast.ImportSpec).Path.Value != `"C"` {
```
Comment (incu6us) [inline reviser/reviser.go:248]: return dd.Specs[0].(*ast.ImportSpec).Path.Value == `"C"`

**Review by incu6us — CHANGES_REQUESTED** [review]

File: reviser/reviser.go (hunk 1 above)
Comment (fmeum) [reply reviser/reviser.go]: Changed it, thanks.
